<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('services', function (Blueprint $t) { $t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('prefix',10);$t->string('status')->default('active');$t->timestamps();});
Schema::create('queues', function (Blueprint $t) { $t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->foreignId('service_id')->constrained()->cascadeOnDelete();$t->string('name');$t->timestamps();});
Schema::create('tickets', function (Blueprint $t) { $t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->foreignId('service_id')->constrained()->cascadeOnDelete();$t->foreignId('queue_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('number');$t->string('code',20);$t->boolean('priority')->default(false);$t->string('status')->default('issued');$t->timestamp('issued_at')->nullable();$t->timestamp('called_at')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->index(['company_id','service_id','created_at']);});
Schema::create('calls', function (Blueprint $t) { $t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('called_at');$t->unsignedSmallInteger('recall_count')->default(0);$t->timestamps();});
Schema::create('attendances', function (Blueprint $t) { $t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('ticket_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
 }
 public function down(): void { Schema::dropIfExists('attendances');Schema::dropIfExists('calls');Schema::dropIfExists('tickets');Schema::dropIfExists('queues');Schema::dropIfExists('services'); }};
